Exit instead of return from bootstrap
In JRuby 9k this fails with an exception like
```
LocalJumpError: unexpected return
  block in classpath:jar-bootstrap.rb at classpath:jar-bootstrap.rb:119
                                 each at org/jruby/RubyArray.java:1560
                                <top> at classpath:jar-bootstrap.rb:114
```
Not sure why this worked in earlier versions of JRuby.